# A linha 'version' pode ser removida, como o aviso sugere.
# version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: healthcare_postgres
    environment:
      # Deixe estas variáveis aqui! Elas ainda são usadas para criar o usuário 'postgres' e a senha 'root'.
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      # Esta linha continua igual, para persistir os dados
      - postgres_data:/var/lib/postgresql/data
      # ESTA É A NOVA LINHA: Mapeia nosso script para dentro do container
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d healthcare"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: healthcare_adminer
    ports:
      - "8081:8080"
    restart: unless-stopped

volumes:
  postgres_data: