spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/healthcare
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none   # usamos Flyway para schema
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
