version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: healthcare_postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"           # expõe a porta 5432 do container para o host
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d healthcare"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: healthcare_adminer
    ports:
      - "8081:8080"
    restart: unless-stopped

volumes:
  postgres_data: